### ISSUE TITLE
Cannot connect to browser ECONNREFUSED

### ISSUE THREAD

**Issue by amite** [weld-io/scraping-service#1]
When I try the base case example provided in the README with hacker news, here is the error I get back in my console:

```
Cannot connect to browser: { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
GET /api/scrape?url=https://news.ycombinator.com&selector=.title+a 400 41.008 ms - 110
```

**Comment by hishamhaniffa** [comment]
same issue

UPDATE:

I was able to get this script work by installing Google Chrome Canary and running it as a headless browser.

**Comment by tomsoderlund** [comment]
@amite @hishamhaniffa I'm running regular Google Chrome 61.0.3163.100 on a Mac.

Did you use the `--headless` option as specified in README?
